# Generated by Django 5.1.4 on 2025-01-03 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
