# Generated by Django 5.1.4 on 2025-01-03 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0002_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
