# Generated by Django 5.1.4 on 2025-01-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0003_rename_username_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
