# Generated by Django 5.1.4 on 2025-01-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discord_app', '0007_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
